name: Quality

on:
  push:
    branches:
      - 'main'
      - 'fix/**'
      - 'feat/**'
      - 'feature/**'
    paths:
      - 'src/**'
      - '**.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: self-hosted
    steps:
      - uses: 69pmb/deploy/workflow/ts-quality@feat/pnpm
        with:
          pnpm-version: 8
  deploy:
    if: github.ref_name == 'main'
    needs: quality
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
